advertisers:
- name: Chime
  domain: chime.com
  category: Finance
  countries:
  - US
  platforms:
    adclarity:
      advertiser_id: '35120415'
      brand_id: '2470'
    sensortower:
      unified_app_id: 55d93e4402ac645ad20fc82a
      publisher_id: 55f8915b8ac350426b02e967
      ios_app_id: '836215269'
      android_package: com.onedebit.chime
- name: Binance
  domain: binance.com
  category: Finance
  countries:
  - US
  - TR
  - BR
  - NG
  platforms:
    adclarity:
      advertiser_id: '19535698'
    sensortower:
      unified_app_id: 59f26235179f4f62e549db39
      publisher_id: 59f26235179f4f62e549db38
      ios_app_id: '1436799971'
      android_package: com.binance.dev
- name: Albert
  domain: albert.com
  category: Games
  countries:
  - US
  platforms:
    adclarity: {}
    sensortower:
      unified_app_id: 55d3a1a302ac64350a000bc2
      publisher_id: 
      ios_app_id: '412786607'
- name: Coinbase
  domain: coinbase.com
  category: Finance
  countries:
  - US
  platforms:
    adclarity: {}
    sensortower:
      unified_app_id: 55af035d9abaa8151307af24
      publisher_id: 
      ios_app_id: '886427730'
      android_package: com.coinbase.android
- name: eToro
  domain: etoro.com
  category: Finance
  countries:
  - US
  platforms:
    adclarity: {}
    sensortower:
      unified_app_id: 54e8fff40f122550510026dd
      publisher_id: 
      ios_app_id: '674984916'
      android_package: com.etoro.openbook
- name: Travel Town
  domain: traveltowngame.com
  category: Games
  countries:
  - US
  platforms:
    adclarity: {}
    sensortower:
      unified_app_id: 5f09e992d871ea7bfa1d261b
      publisher_id: 
      ios_app_id: '1521236603'
      android_package: io.randomco.travel
- name: Pokemon GO
  domain: pokemongolive.com
  category: Games
  countries:
  - US
  platforms:
    adclarity: {}
    sensortower:
      unified_app_id: 577c9fa40211a6cf30000056
      publisher_id: 
      ios_app_id: '1094591345'
      android_package: com.nianticlabs.pokemongo
- name: Royal Match
  domain: royalmatch.com
  category: Games
  countries:
  - US
  platforms:
    adclarity: {}
    sensortower:
      unified_app_id: 5f16a8019f7b275235017614
      publisher_id: 
      ios_app_id: '1482155847'
      android_package: com.dreamgames.royalmatch
- name: MoneyLion
  domain: moneylion.com
  category: Finance
  countries:
  - US
  platforms:
    adclarity: {}
    sensortower:
      unified_app_id: 56aeb27302ac64713d000002
      publisher_id: 
      ios_app_id: '1064677082'
      android_package: com.moneylion
- name: Kraken
  domain: kraken.com
  category: Finance
  countries:
  - US
  platforms:
    adclarity: {}
    sensortower:
      unified_app_id: 5f7507d3dbcdf6195491db76
      publisher_id: 
      ios_app_id: '1481947260'
      android_package: com.kraken.invest.app

- name: Current
  domain: current.com
  category: Finance
  countries:
  - US
  platforms:
    sensortower:
      unified_app_id: 5703b61402ac643f4b000061
      publisher_id:
      ios_app_id: '1077366211'
      android_package: com.current.app

- name: Dave
  domain: dave.com
  category: Finance
  countries:
  - US
  platforms:
    sensortower:
      unified_app_id: 58ff690a0211a6a9730005c3
      publisher_id:
      ios_app_id: '1193801909'
      android_package: com.dave

- name: Koho
  domain: koho.ca
  category: Finance
  countries:
  - CA
  platforms:
    sensortower:
      unified_app_id: 58873af20211a6fd3e00006e
      publisher_id:
      ios_app_id: '1091010942'
      android_package: ca.koho

- name: Mistplay
  domain: mistplay.com
  category: Games
  countries:
  - US
  platforms:
    sensortower:
      unified_app_id: 578479f10211a6876500007d
      publisher_id:
      ios_app_id: '6739352969'
      android_package: com.mistplay.mistplay

- name: MonopolyGo
  domain: monopolygo.com
  category: Games
  countries:
  - US
  platforms:
    sensortower:
      unified_app_id: 62be6a5fbab10c69c5a0a42a
      publisher_id:
      ios_app_id: '1621328561'
      android_package: com.scopely.monopolygo

- name: Possible Finance
  domain: possiblefinance.com
  category: Finance
  countries:
  - US
  platforms:
    sensortower:
      unified_app_id: 5b074b73cab16e72da8cf77d
      publisher_id:
      ios_app_id: '1380384597'
      android_package: com.possible_mobile

- name: Realtor
  domain: realtor.com
  category: Lifestyle, Business
  countries:
  - US
  platforms:
    sensortower:
      unified_app_id: 55c515af02ac64f9c000264a
      publisher_id:
      ios_app_id: '336698281'
      android_package: com.move.realtor

- name: ScrabbleGo
  domain: scrabblego.com
  category: Games
  countries:
  - US
  platforms:
    sensortower:
      unified_app_id: 5a39e9681454d22f5a5e75ca
      publisher_id:
      ios_app_id: '1215933788'
      android_package: com.pieyel.scrabble

- name: Shopback
  domain: shopback.com
  category: Shopping, Lifestyle
  countries:
  - US
  platforms:
    sensortower:
      unified_app_id: 57469e54bd495109ce00220f
      publisher_id:
      ios_app_id: '1086505626'
      android_package: com.shopback.app

- name: Stash
  domain: stash.com
  category: Finance, Education
  countries:
  - US
  platforms:
    sensortower:
      unified_app_id: 56fddbd82839d9aa34000001
      publisher_id:
      ios_app_id: '1017148055'
      android_package: com.stash.stashinvest

- name: Tilt
  domain: tilt.com
  category: Finance, Productivity
  countries:
  - US
  platforms:
    sensortower:
      unified_app_id: 591206890211a6ffc9002173
      publisher_id:
      ios_app_id: '1136397354'
      android_package: finance.empower

- name: Upside
  domain: upside.com
  category: Travel, Shopping
  countries:
  - US
  platforms:
    sensortower:
      unified_app_id: 5717b62602ac64c3a60000fe
      publisher_id:
      ios_app_id: '1099997174'
      android_package: com.upside.consumer.android

# - name: Varo
#   category: Finance, Shopping
#   countries:
#   - US
#   platforms:
#     sensortower:
#       unified_app_id: 594380950211a6039a0002ad
#       publisher_id:
#       ios_app_id: '1517676784'
#       android_package: com.varomoney.bank

# - name: freecash
#   category: Finance, Entertainment
#   countries:
#   - US
#   platforms:
#     sensortower:
#       unified_app_id: 625b7c37117ba052b27c165b
#       publisher_id:
#       ios_app_id: '1673567402'
#       android_package: com.freecash.app2

- name: swagbucks
  domain: swagbucks.com
  category: Lifestyle, Shopping
  countries:
  - US
  platforms:
    sensortower:
      unified_app_id: 55c5540a02ac64f9c00033f8
      publisher_id:
      ios_app_id: '640439547'
      android_package: com.prodege.swagbucksmobile

- name: testerup
  domain: testerup.com
  category: Finance
  countries:
  - US
  platforms:
    sensortower:
      unified_app_id: 594dc76b0162376fcb0093c9
      publisher_id:
      ios_app_id: '1241984225'
      android_package: de.empfohlen
