advertisers:
  - name: Chime
    countries:
      - US
  - name: Binance
    countries:
      - US
      - TR
      - BR
      - NG
  - name: Albert
    countries:
      - US
  - name: Coinbase
    countries:
      - US
  - name: eToro
    countries:
      - US
  - name: Travel Town
    countries:
      - US
  - name: Pokemon GO
    countries:
      - US
  - name: Royal Match
    countries:
      - US
  - name: MoneyLion
    countries:
      - US
  - name: Kraken
    countries:
      - US
  - name: Current
    countries:
      - US
  - name: Dave
    countries:
      - US
  - name: Koho
    countries:
      - US
  - name: Mistplay
    countries:
      - US
  - name: MonopolyGo
    countries:
      - US
  - name: Possible Finance
    countries:
      - US
  - name: Realtor
    countries:
      - US
  - name: ScrabbleGo
    countries:
      - US
  - name: Shopback
    countries:
      - US
  - name: Stash
    countries:
      - US
  - name: Tilt
    countries:
      - US
  - name: Upside
    countries:
      - US
  - name: swagbucks
    countries:
      - US
  - name: testerup
    countries:
      - US
