start_date: "2026-03-05"
end_date: "2026-04-06"
services:
  - ChatGPT
  - Perplexity
  - Google AI Overview
  - Microsoft Copilot
targets:
  - brand: binance.com
    country: us
  - brand: binance.com
    country: tr
  - brand: binance.com
    country: br
  - brand: binance.com
    country: ng
  - brand: albert.com
    country: us
  - brand: coinbase.com
    country: us
  - brand: etoro.com
    country: us
  - brand: traveltowngame.com
    country: us
  - brand: moneylion.com
    country: us
  - brand: kraken.com
    country: us
  - brand: possiblefinance.com
    country: us
  - brand: realtor.com
    country: us
  - brand: shopback.com
    country: us
  - brand: stash.com
    country: us
  - brand: tilt.com
    country: us
  - brand: swagbucks.com
    country: us
  - brand: testerup.com
    country: us
